[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
src_dir = firmware
monitor_speed = 115200

lib_deps =
  tzapu/WiFiManager @ ^2.0.17
  bblanchon/ArduinoJson @ ^6.21.5
  mandulaj/PZEM-004T-v30 @ ^1.1.2
